import './helpers/test-env.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { openMessageStore } from '../src/message-store.js';
import * as todo from '../src/owner-todo.js';
import { mailboxFolders } from '../src/messages.js';

const now = Date.now();
const env = { HERDR_ENV: '1', HERDR_PANE_ID: 'wB:p1', HERDR_WORKSPACE_ID: 'wB' };
const control = { projects: { alpha: { workspace: 'wA', orch: { pane: 'wA:p1' } } } };
for (const backend of ['json', 'sqlite']) test(`${backend}: migration imports open Owner asks once by project and title key`, (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'todo-migration-'));
  const store = openMessageStore({ dir, backend });
  t.after(() => { store.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  const context = { dir, store, env, now, control, herdr: () => ({ id: 'wB:p1', workspace: 'wB', label: 'boss' }) };
  const fields = { thread: 'alpha', from: 'orch', to: 'owner', kind: 'reply', action: 'answer', text: 'Check the preview\n\nPlease check the labels.' };
  const original = store.append(fields, { now: now - 60000 });
  store.append({ ...fields, text: '  CHECK   the preview\n\nSame ask.' }, { now: now - 59000 });
  store.append({ ...fields, thread: 'boss', from: 'boss', kind: 'report', title: 'Choose the next step', action: 'decide', text: 'Choose Accept or Deny.' }, { now });
  store.append({ ...fields, text: 'Closed ask', closedAt: new Date(now).toISOString() }, { now });
  store.append({ ...fields, action: 'read', text: 'Information only' }, { now });
  store.append({ ...fields, kind: 'agent', text: 'Agent only' }, { now });
  const answered = store.append({ ...fields, text: 'Already answered' }, { now });
  store.append({ thread: 'alpha', from: 'owner', to: 'orch', kind: 'message', text: 'Finished.', replyTo: answered.id }, { now });
  const result = todo.migrateTodo({}, context);
  assert.equal(result.imported, 2);
  assert.equal(todo.migrateTodo({}, context).imported, 0);
  const list = todo.todoView(store.all()).todo;
  assert.equal(list.length, 2);
  const imported = list.find((item) => item.project === 'alpha');
  assert.equal(imported.key, 'alpha:check the preview');
  assert.equal(imported.createdAt, original.at);
  assert.deepEqual(imported.poster, { role: 'orch', pane: 'wA:p1', workspace: 'wA' });
  assert.ok(imported.steps.includes('Please check the labels.'));
  assert.deepEqual(mailboxFolders(store.all()).needsYou.map((item) => item.id), [answered.id]);
  assert.equal(store.all().find((record) => record.id === original.id).closedBy, 'todo');
  todo.actOnTodo({ id: imported.id, action: 'done' }, context);
  store.append(fields, { now: now + 1000 });
  assert.equal(todo.migrateTodo({}, context).imported, 0, 'a terminal import is not reopened on replay');
  assert.equal(store.all().find((record) => record.id === imported.id).state, 'done');
});

test('migration refuses an orchestrator and masks private legacy content before importing', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'todo-migration-safe-'));
  const store = openMessageStore({ dir });
  t.after(() => { store.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  const context = { dir, store, env, now, control, herdr: () => ({ id: 'wB:p1', workspace: 'wB', label: 'boss' }) };
  const privateText = 'password=' + 'invented'.repeat(4);
  const privateMarker = '-----BEGIN ' + 'PRIVATE KEY-----';
  store.append({ thread: 'alpha', from: 'orch', to: 'owner', kind: 'reply', action: 'approve', text: 'Grant access\n' + privateText + '\nhttps://sample-host.invalid.net/check\n' + privateMarker }, { now });
  assert.throws(() => todo.migrateTodo({}, { ...context, herdr: () => ({ id: 'wB:p1', workspace: 'wB', label: 'orch' }), control: { projects: { beta: { workspace: 'wB' } } } }), (error) => error.status === 403);
  assert.equal(todo.migrateTodo({}, context).imported, 1);
  const item = store.all().find((record) => record.kind === 'todo');
  assert.ok(!item.text.includes(privateText));
  assert.ok(!item.text.includes('sample-host.invalid.net'));
  assert.ok(!item.text.includes(privateMarker));
});
